import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./list.css";
import "./page.css";
import {ViewTransitions} from "next-view-transitions";
import Nav from "./component/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Wolf Hunter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Nav />
        <div className="pt-[85px]">{children}</div>
      </body>
    </html>
    </ViewTransitions>
  );
}
